import { PageHero } from "@/components/page-elements";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Terms & Conditions", description: "Read the terms governing access to and use of the public ALVITEQ company website.", path: "/terms" });

export default function TermsPage() {
  return <><PageHero eyebrow="Legal" title="Terms & Conditions" intro="These terms govern access to and use of the public ALVITEQ website." />
    <article className="legal container"><p className="legal-date">Effective 29 July 2026</p><h2>1. Informational website</h2><p>The website provides general company and product information. Content may change as products develop and is not legal, financial, medical, records-management, or other professional advice.</p><h2>2. Product availability</h2><p>Descriptions may discuss planned, developing, platform-dependent, or limited capabilities. Availability can vary by operating system, device hardware, region, release channel, and product version.</p><h2>3. Product-specific terms</h2><p>Downloading or using an ALVITEQ product may require acceptance of separate agreements, privacy notices, and platform terms. Website content does not replace those product-specific terms.</p><h2>4. Intellectual property</h2><p>ALVITEQ branding, product names, interface designs, illustrations, text, and original materials are protected by applicable intellectual-property laws. No website use grants a right to misrepresent affiliation or endorsement.</p><h2>5. Acceptable use</h2><p>You must not interfere with website operation, attempt unauthorized access, introduce malicious code, scrape in a manner that degrades service, or use content unlawfully.</p><h2>6. External services</h2><p>Third-party links and infrastructure are governed by their providers. ALVITEQ is not responsible for external content or service availability.</p><h2>7. Disclaimer and liability</h2><p>The website is provided on an “as available” basis. To the extent permitted by law, ALVITEQ disclaims implied warranties and is not liable for indirect or consequential losses arising solely from use of this informational website.</p><h2>8. Contact</h2><p>Questions about these terms may be sent to <a href="mailto:legal@alviteq.com">legal@alviteq.com</a>.</p></article>
  </>;
}
