import { PageHero } from "@/components/page-elements";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Privacy Policy", description: "Learn how information is handled when you visit the ALVITEQ website or contact the company.", path: "/privacy" });

export default function PrivacyPage() {
  return <><PageHero eyebrow="Legal" title="Privacy Policy" intro="This policy explains the limited information involved when you visit the ALVITEQ website or contact us." />
    <article className="legal container"><p className="legal-date">Effective 29 July 2026</p><h2>1. Scope</h2><p>This policy applies to the public website at alviteq.com and direct correspondence about Alviteq. OwnKeep presents separate in-product notices and agreements for vault use.</p><h2>2. Website delivery data</h2><p>Cloudflare may process technical request information such as IP address, browser details, timestamps, requested pages, and security signals to deliver, protect, and operate the website. ALVITEQ does not currently provide website user accounts or advertising trackers.</p><h2>3. Information you provide</h2><p>If you email ALVITEQ, we receive the address, message, attachments, and other information you choose to provide. We use it to respond, manage the relationship, prevent abuse, and maintain necessary business records.</p><h2>4. Sensitive information</h2><p>Do not send vault recovery passphrases, passwords, identity documents, or private OwnKeep records by email. ALVITEQ does not need those items to answer normal enquiries.</p><h2>5. Sharing and retention</h2><p>Information may be processed by service providers used for website delivery and business communication, or disclosed when legally required. Correspondence is retained only as reasonably needed for the enquiry, security, legal obligations, and legitimate business records.</p><h2>6. Your choices</h2><p>You may ask about personal information submitted through direct correspondence, subject to applicable legal limitations. Contact <a href="mailto:privacy@alviteq.com">privacy@alviteq.com</a>.</p><h2>7. Changes</h2><p>Material updates will be published on this page with a revised effective date.</p></article>
  </>;
}
